"use client";

import type {
  ChatPanelContentProps,
  ChatPanelConversationContentProps,
  ChatPanelManagementContentProps,
} from "./chat-panel-content.types";

export function buildChatPanelConversationContentProps({
  activeConversationId,
  canWriteWorkspace,
  conversations,
  draft,
  error,
  handleSend,
  handleSyncNotifications,
  loading,
  messages,
  onCreateConversation,
  onSelectConversation,
  setDraft,
  syncing,
}: ChatPanelContentProps): ChatPanelConversationContentProps {
  return {
    activeConversationId,
    canWriteWorkspace,
    conversations,
    draft,
    error,
    handleSend,
    handleSyncNotifications,
    loading,
    messages,
    onCreateConversation,
    onSelectConversation,
    setDraft,
    syncing,
  };
}

export function buildChatPanelManagementContentProps({
  auditLogs,
  canManageSharing,
  canManageWorkspace,
  creatingShare,
  disablingShareId,
  handleCreateShareLink,
  handleDisableShareLink,
  handleRefreshAuditLogs,
  handleReindexKnowledge,
  knowledgeStats,
  latestShareUrl,
  notifications,
  onMarkNotificationRead,
  refreshingAudit,
  reindexing,
  setShareMaxUses,
  setShareName,
  setSharePermission,
  shareLinks,
  shareMaxUses,
  shareName,
  sharePermission,
  unreadCount,
}: ChatPanelContentProps): ChatPanelManagementContentProps {
  return {
    auditLogs,
    canManageSharing,
    canManageWorkspace,
    creatingShare,
    disablingShareId,
    handleCreateShareLink,
    handleDisableShareLink,
    handleRefreshAuditLogs,
    handleReindexKnowledge,
    knowledgeStats,
    latestShareUrl,
    notifications,
    onMarkNotificationRead,
    refreshingAudit,
    reindexing,
    setShareMaxUses,
    setShareName,
    setSharePermission,
    shareLinks,
    shareMaxUses,
    shareName,
    sharePermission,
    unreadCount,
  };
}
