"use client";
import { useStoredLocale } from "../lib/locale";
import { buildMediaAssetCardProcessingStatusTagProps } from "./media-asset-card-processing-status-tag-props"; import { buildMediaAssetCardSizeTagProps } from "./media-asset-card-size-tag-props";
import { buildMediaAssetCardExtractionModeTagProps } from "./media-asset-card-extraction-mode-tag-props"; import { buildMediaAssetCardFileExtensionTagProps } from "./media-asset-card-file-extension-tag-props"; import { buildMediaAssetCardProcessingSourceTagProps } from "./media-asset-card-processing-source-tag-props"; import { buildMediaAssetCardRemoteFetchTagProps } from "./media-asset-card-remote-fetch-tag-props"; import { buildMediaAssetCardRetryCountTagProps } from "./media-asset-card-retry-count-tag-props"; import { buildMediaAssetCardRetryStateTagProps } from "./media-asset-card-retry-state-tag-props"; import { buildMediaAssetCardStorageProviderTagProps } from "./media-asset-card-storage-provider-tag-props";
import { MediaAssetCardExtractionModeTag } from "./media-asset-card-extraction-mode-tag";
import { MediaAssetCardFileExtensionTag } from "./media-asset-card-file-extension-tag"; import { MediaAssetCardProcessingSourceTag } from "./media-asset-card-processing-source-tag";
import { readMediaAssetCardMetadataTagValues } from "./media-asset-card-metadata-tag-values";
import { MediaAssetCardProcessingStatusTag } from "./media-asset-card-processing-status-tag"; import { MediaAssetCardRemoteFetchTag } from "./media-asset-card-remote-fetch-tag";
import { MediaAssetCardRetryCountTag } from "./media-asset-card-retry-count-tag"; import { MediaAssetCardRetryStateTag } from "./media-asset-card-retry-state-tag";
import { MediaAssetCardSizeTag } from "./media-asset-card-size-tag"; import { MediaAssetCardStorageProviderTag } from "./media-asset-card-storage-provider-tag"; import type { MediaAssetCardMetadataTagsProps } from "./media-asset-card-metadata-tags.types";
export function MediaAssetCardMetadataTags(props: MediaAssetCardMetadataTagsProps) {
  const { locale } = useStoredLocale(), builderProps = { ...props, locale, ...readMediaAssetCardMetadataTagValues({ asset: props.asset }) };
  return <div className="tag-row"><MediaAssetCardProcessingStatusTag {...buildMediaAssetCardProcessingStatusTagProps(builderProps)} /><MediaAssetCardStorageProviderTag {...buildMediaAssetCardStorageProviderTagProps(builderProps)} /><MediaAssetCardSizeTag {...buildMediaAssetCardSizeTagProps(builderProps)} /><MediaAssetCardProcessingSourceTag {...buildMediaAssetCardProcessingSourceTagProps(builderProps)} /><MediaAssetCardExtractionModeTag {...buildMediaAssetCardExtractionModeTagProps(builderProps)} /><MediaAssetCardRemoteFetchTag {...buildMediaAssetCardRemoteFetchTagProps(builderProps)} /><MediaAssetCardRetryStateTag {...buildMediaAssetCardRetryStateTagProps(builderProps)} /><MediaAssetCardRetryCountTag {...buildMediaAssetCardRetryCountTagProps(builderProps)} /><MediaAssetCardFileExtensionTag {...buildMediaAssetCardFileExtensionTagProps(builderProps)} /></div>;
}
