"use client";
import { useStoredLocale } from "../lib/locale";
import { readMetadataNumber, readMetadataText } from "../lib/record-panel-media";
import { MediaAssetCardExtractionModeTag } from "./media-asset-card-extraction-mode-tag";
import { MediaAssetCardFileExtensionTag } from "./media-asset-card-file-extension-tag"; import { MediaAssetCardProcessingSourceTag } from "./media-asset-card-processing-source-tag";
import { MediaAssetCardProcessingStatusTag } from "./media-asset-card-processing-status-tag"; import { MediaAssetCardRetryCountTag } from "./media-asset-card-retry-count-tag"; import { MediaAssetCardRemoteFetchTag } from "./media-asset-card-remote-fetch-tag";
import { MediaAssetCardRetryStateTag } from "./media-asset-card-retry-state-tag"; import { MediaAssetCardSizeTag } from "./media-asset-card-size-tag"; import { MediaAssetCardStorageProviderTag } from "./media-asset-card-storage-provider-tag"; import type { MediaAssetCardMetadataTagsProps } from "./media-asset-card-metadata-tags.types";
export function MediaAssetCardMetadataTags({ asset, mediaIssueCopy }: MediaAssetCardMetadataTagsProps) {
  const { locale } = useStoredLocale(), extractionMode = readMetadataText(asset.metadata_json, "extraction_mode"), processingSource = readMetadataText(asset.metadata_json, "processing_source"), remoteFetchStatus = readMetadataText(asset.metadata_json, "remote_fetch_status"), retryState = readMetadataText(asset.metadata_json, "processing_retry_state"), retryCount = readMetadataNumber(asset.metadata_json, "processing_retry_count"), retryMaxAttempts = readMetadataNumber(asset.metadata_json, "processing_retry_max_attempts");
  return <div className="tag-row"><MediaAssetCardProcessingStatusTag asset={asset} locale={locale} /><MediaAssetCardStorageProviderTag asset={asset} locale={locale} /><MediaAssetCardSizeTag asset={asset} /><MediaAssetCardProcessingSourceTag processingSource={processingSource} /><MediaAssetCardExtractionModeTag extractionMode={extractionMode} /><MediaAssetCardRemoteFetchTag locale={locale} mediaIssueCopy={mediaIssueCopy} remoteFetchStatus={remoteFetchStatus} /><MediaAssetCardRetryStateTag locale={locale} mediaIssueCopy={mediaIssueCopy} retryState={retryState} /><MediaAssetCardRetryCountTag mediaIssueCopy={mediaIssueCopy} retryCount={retryCount} retryMaxAttempts={retryMaxAttempts} /><MediaAssetCardFileExtensionTag asset={asset} /></div>;
}
