"use client";

import { RecordBrowseWorkspace } from "./record-browse-workspace";
import { RecordEditorWorkspace } from "./record-editor-workspace";
import { RecordPanelHeader } from "./record-panel-header";
import type { RecordPanelV2Props } from "./record-panel-v2.types";
import {
  buildRecordBrowseWorkspaceProps,
  buildRecordEditorWorkspaceProps,
} from "./record-panel-v2-workspace-props";
import { useRecordPanelController } from "./use-record-panel-controller";

export function RecordPanelV2({
  authToken,
  canWriteWorkspace,
  workspaceId,
  records,
  selectedRecordId,
  timelineDays,
  mediaAssets,
  mediaDeadLetterOverview,
  mediaProcessingOverview,
  mediaStorageSummary,
  reminders,
  onSelectRecord,
  onSaveRecord,
  onCreateReminder,
  onDeleteMedia,
  onUpdateReminder,
  onDeleteReminder,
  onDeleteRecord,
  onBulkRetryMediaDeadLetter,
  onRefreshMediaStatus,
  onApplyRecordFilter,
  onApplyLocationFilter,
  onCreateSearchPreset,
  onDeleteSearchPreset,
  onRetryMedia,
  onUploadMedia,
  onResetFilter,
  recordFilter,
  searchPresets,
  savingSearchPreset,
  filteringRecords,
}: RecordPanelV2Props) {
  const {
    locale,
    avoidCount,
    foodCount,
    selectedRecord,
    form,
    setForm,
    saving,
    deleting,
    uploading,
    refreshingMediaId,
    retryingMediaId,
    bulkRetryingDeadLetter,
    downloadingMediaId,
    deletingMediaId,
    reminderForm,
    setReminderForm,
    savingReminder,
    locationReviewForm,
    setLocationReviewForm,
    viewMode,
    setViewMode,
    filterDraft,
    setFilterDraft,
    presetName,
    setPresetName,
    selectedDeadLetterIds,
    error,
    selectedLocationReview,
    selectedLocationHistory,
    selectedRecordMediaSizeLabel,
    mediaIssueCopy,
    panelCopy,
    detailCopy,
    formatAvoidCountLabel,
    formatFileCountLabel,
    formatHistoryTimestampLabel,
    formatRecordTimestampLabel,
    formatReminderEnabledLabel,
    formatReminderStatusLabel,
    formatReminderTimestampLabel,
    formatReviewStatusLabel,
    formatTimelineCountLabel,
    formatTimelineDateLabel,
    summarizeHistoryActionLabel,
    summarizeRecordFilterLabel,
    handleSubmit,
    handleDelete,
    handleUpload,
    handleCreateReminderSubmit,
    handleRefreshMedia,
    handleRetryMediaProcessing,
    handleToggleDeadLetterSelection,
    handleSelectAllDeadLetter,
    handleClearDeadLetterSelection,
    handleBulkRetryDeadLetter,
    handleDownloadMedia,
    handleDeleteMediaAsset,
    handleApplyFilter,
    handleSavePreset,
    handleDeletePreset,
  } = useRecordPanelController({
    authToken,
    workspaceId,
    records,
    selectedRecordId,
    mediaAssets,
    mediaDeadLetterOverview,
    onSaveRecord,
    onCreateReminder,
    onDeleteMedia,
    onDeleteRecord,
    onBulkRetryMediaDeadLetter,
    onRefreshMediaStatus,
    onApplyRecordFilter,
    onCreateSearchPreset,
    onDeleteSearchPreset,
    onRetryMedia,
    onUploadMedia,
    recordFilter,
  });
  const browseWorkspaceProps = buildRecordBrowseWorkspaceProps({
    canWriteWorkspace,
    records,
    timelineDays,
    selectedRecordId,
    recordFilter,
    searchPresets,
    onApplyLocationFilter,
    onApplyRecordFilter,
    onResetFilter,
    onSelectRecord,
    avoidCount,
    detailCopy,
    filterDraft,
    filteringRecords,
    foodCount,
    form,
    formatAvoidCountLabel,
    formatRecordTimestampLabel,
    formatReviewStatusLabel,
    formatTimelineCountLabel,
    formatTimelineDateLabel,
    handleApplyFilter,
    handleDeletePreset,
    handleSavePreset,
    panelCopy,
    presetName,
    savingSearchPreset,
    setFilterDraft,
    setForm,
    setPresetName,
    setViewMode,
    summarizeRecordFilterLabel,
    viewMode,
  });
  const editorWorkspaceProps = buildRecordEditorWorkspaceProps({
    authToken,
    canWriteWorkspace,
    workspaceId,
    mediaAssets,
    mediaDeadLetterOverview,
    mediaProcessingOverview,
    mediaStorageSummary,
    reminders,
    onDeleteReminder,
    onUpdateReminder,
    bulkRetryingDeadLetter,
    deleting,
    deletingMediaId,
    detailCopy,
    downloadingMediaId,
    error,
    form,
    formatFileCountLabel,
    formatHistoryTimestampLabel,
    formatReminderEnabledLabel,
    formatReminderStatusLabel,
    formatReminderTimestampLabel,
    formatReviewStatusLabel,
    handleBulkRetryDeadLetter,
    handleClearDeadLetterSelection,
    handleCreateReminderSubmit,
    handleDelete,
    handleDeleteMediaAsset,
    handleDownloadMedia,
    handleRefreshMedia,
    handleRetryMediaProcessing,
    handleSelectAllDeadLetter,
    handleSubmit,
    handleToggleDeadLetterSelection,
    handleUpload,
    locale,
    locationReviewForm,
    mediaIssueCopy,
    panelCopy,
    refreshingMediaId,
    reminderForm,
    retryingMediaId,
    saving,
    savingReminder,
    selectedDeadLetterIds,
    selectedLocationHistory,
    selectedLocationReview,
    selectedRecord,
    selectedRecordMediaSizeLabel,
    setForm,
    setLocationReviewForm,
    setReminderForm,
    summarizeHistoryActionLabel,
    uploading,
  });

  return (
    <section className="panel">
      <RecordPanelHeader
        canWriteWorkspace={canWriteWorkspace}
        onCreateRecord={() => onSelectRecord(null)}
        panelCopy={panelCopy}
        workspaceId={workspaceId}
      />
      <div className="panel-body">
        <RecordBrowseWorkspace {...browseWorkspaceProps} />
        <RecordEditorWorkspace {...editorWorkspaceProps} />
      </div>
    </section>
  );
}
