import type {
  BuildRecordEditorWorkspacePropsInput,
  RecordEditorWorkspaceProps,
} from "./record-panel-v2-workspace-props.types";

export function buildRecordEditorWorkspaceProps({
  authToken,
  canWriteWorkspace,
  workspaceId,
  mediaAssets,
  mediaDeadLetterOverview,
  mediaProcessingOverview,
  mediaStorageSummary,
  reminders,
  onDeleteReminder,
  onUpdateReminder,
  bulkRetryingDeadLetter,
  deleting,
  deletingMediaId,
  detailCopy,
  downloadingMediaId,
  error,
  form,
  formatFileCountLabel,
  formatHistoryTimestampLabel,
  formatReminderEnabledLabel,
  formatReminderStatusLabel,
  formatReminderTimestampLabel,
  formatReviewStatusLabel,
  handleBulkRetryDeadLetter,
  handleClearDeadLetterSelection,
  handleCreateReminderSubmit,
  handleDelete,
  handleDeleteMediaAsset,
  handleDownloadMedia,
  handleRefreshMedia,
  handleRetryMediaProcessing,
  handleSelectAllDeadLetter,
  handleSubmit,
  handleToggleDeadLetterSelection,
  handleUpload,
  locale,
  locationReviewForm,
  mediaIssueCopy,
  panelCopy,
  refreshingMediaId,
  reminderForm,
  retryingMediaId,
  saving,
  savingReminder,
  selectedDeadLetterIds,
  selectedLocationHistory,
  selectedLocationReview,
  selectedRecord,
  selectedRecordMediaSizeLabel,
  setForm,
  setLocationReviewForm,
  setReminderForm,
  summarizeHistoryActionLabel,
  uploading,
}: BuildRecordEditorWorkspacePropsInput): RecordEditorWorkspaceProps {
  return {
    authToken,
    bulkRetryingDeadLetter,
    canWriteWorkspace,
    channelInAppLabel: detailCopy.channelInApp,
    channelLabel: detailCopy.channelLabel,
    createReminderLabel: detailCopy.createReminder,
    deleteReminderLabel: detailCopy.deleteReminder,
    deleting,
    deletingMediaId,
    downloadingMediaId,
    enableReminderLabel: detailCopy.enableReminder,
    error,
    form,
    formatFileCountLabel,
    formatHistoryTimestampLabel,
    formatReminderEnabledLabel,
    formatReminderStatusLabel,
    formatReminderTimestampLabel,
    formatReviewStatusLabel,
    largestFilePrefixLabel: detailCopy.largestFilePrefix,
    locale,
    locationReviewForm,
    markReminderDoneLabel: detailCopy.markReminderDone,
    mediaAssets,
    mediaDeadLetterOverview,
    mediaIssueCopy,
    mediaProcessingOverview,
    mediaStorageSummary,
    noMediaLabel: detailCopy.noMedia,
    noRemindersLabel: detailCopy.noReminders,
    onBulkRetryAllDeadLetter: () => handleBulkRetryDeadLetter("all"),
    onBulkRetrySelectedDeadLetter: () => handleBulkRetryDeadLetter("selected"),
    onClearDeadLetterSelection: handleClearDeadLetterSelection,
    onCreateReminder: handleCreateReminderSubmit,
    onDelete: handleDelete,
    onDeleteMediaAsset: handleDeleteMediaAsset,
    onDeleteReminder,
    onDownloadMedia: handleDownloadMedia,
    onRefreshMedia: handleRefreshMedia,
    onRetryMediaProcessing: handleRetryMediaProcessing,
    onSelectAllDeadLetter: handleSelectAllDeadLetter,
    onSubmit: handleSubmit,
    onToggleDeadLetterSelection: handleToggleDeadLetterSelection,
    onUpdateReminder,
    onUpload: handleUpload,
    panelCopy,
    pauseReminderLabel: detailCopy.pauseReminder,
    refreshingMediaId,
    reminderForm,
    reminderNoteLabel: detailCopy.reminderNoteLabel,
    reminderNotePlaceholder: detailCopy.reminderNotePlaceholder,
    reminderSectionDescription: detailCopy.reminderSectionDescription,
    reminderSectionTitle: detailCopy.reminderSectionTitle,
    reminderTitleLabel: detailCopy.reminderTitleLabel,
    reminderTitlePlaceholder: detailCopy.reminderTitlePlaceholder,
    remindAtLabel: detailCopy.remindAtLabel,
    reminders,
    retryingMediaId,
    saving,
    savingReminder,
    savingReminderLabel: detailCopy.savingReminder,
    selectedDeadLetterIds,
    selectedLocationHistory,
    selectedLocationReview,
    selectedRecord,
    selectedRecordMediaSizeLabel,
    setForm,
    setLocationReviewForm,
    setReminderForm,
    summarizeHistoryActionLabel,
    untitledReminderLabel: detailCopy.untitledReminder,
    uploading,
    workspaceId,
  };
}
