import type {
  BuildRecordEditorWorkspacePropsInput,
  RecordEditorWorkspaceProps,
} from "./record-panel-v2-workspace-props.types";

export type BuildRecordEditorWorkspaceBasePropsInput = Pick<
  BuildRecordEditorWorkspacePropsInput,
  | "authToken"
  | "bulkRetryingDeadLetter"
  | "canWriteWorkspace"
  | "deleting"
  | "deletingMediaId"
  | "downloadingMediaId"
  | "error"
  | "form"
  | "formatFileCountLabel"
  | "formatHistoryTimestampLabel"
  | "formatReminderEnabledLabel"
  | "formatReminderStatusLabel"
  | "formatReminderTimestampLabel"
  | "formatReviewStatusLabel"
  | "locale"
  | "locationReviewForm"
  | "mediaAssets"
  | "mediaDeadLetterOverview"
  | "mediaIssueCopy"
  | "mediaProcessingOverview"
  | "mediaStorageSummary"
  | "panelCopy"
  | "refreshingMediaId"
  | "reminderForm"
  | "reminders"
  | "retryingMediaId"
  | "saving"
  | "savingReminder"
  | "selectedDeadLetterIds"
  | "selectedLocationHistory"
  | "selectedLocationReview"
  | "selectedRecord"
  | "selectedRecordMediaSizeLabel"
  | "setForm"
  | "setLocationReviewForm"
  | "setReminderForm"
  | "summarizeHistoryActionLabel"
  | "uploading"
  | "workspaceId"
>;

export type RecordEditorWorkspaceBaseProps = Pick<
  RecordEditorWorkspaceProps,
  | "authToken"
  | "bulkRetryingDeadLetter"
  | "canWriteWorkspace"
  | "deleting"
  | "deletingMediaId"
  | "downloadingMediaId"
  | "error"
  | "form"
  | "formatFileCountLabel"
  | "formatHistoryTimestampLabel"
  | "formatReminderEnabledLabel"
  | "formatReminderStatusLabel"
  | "formatReminderTimestampLabel"
  | "formatReviewStatusLabel"
  | "locale"
  | "locationReviewForm"
  | "mediaAssets"
  | "mediaDeadLetterOverview"
  | "mediaIssueCopy"
  | "mediaProcessingOverview"
  | "mediaStorageSummary"
  | "panelCopy"
  | "refreshingMediaId"
  | "reminderForm"
  | "reminders"
  | "retryingMediaId"
  | "saving"
  | "savingReminder"
  | "selectedDeadLetterIds"
  | "selectedLocationHistory"
  | "selectedLocationReview"
  | "selectedRecord"
  | "selectedRecordMediaSizeLabel"
  | "setForm"
  | "setLocationReviewForm"
  | "setReminderForm"
  | "summarizeHistoryActionLabel"
  | "uploading"
  | "workspaceId"
>;
