import type {
  BuildRecordEditorWorkspacePropsInput,
  RecordEditorWorkspaceProps,
} from "./record-panel-v2-workspace-props.types";
import { buildRecordEditorWorkspaceActionProps } from "./record-panel-v2-editor-workspace-action-props";
import { buildRecordEditorWorkspaceBaseProps } from "./record-panel-v2-editor-workspace-base-props";
import { buildRecordEditorWorkspaceCopyProps } from "./record-panel-v2-editor-workspace-copy-props";

export function buildRecordEditorWorkspaceProps({
  authToken,
  canWriteWorkspace,
  workspaceId,
  mediaAssets,
  mediaDeadLetterOverview,
  mediaProcessingOverview,
  mediaStorageSummary,
  reminders,
  onDeleteReminder,
  onUpdateReminder,
  bulkRetryingDeadLetter,
  deleting,
  deletingMediaId,
  detailCopy,
  downloadingMediaId,
  error,
  form,
  formatFileCountLabel,
  formatHistoryTimestampLabel,
  formatReminderEnabledLabel,
  formatReminderStatusLabel,
  formatReminderTimestampLabel,
  formatReviewStatusLabel,
  handleBulkRetryDeadLetter,
  handleClearDeadLetterSelection,
  handleCreateReminderSubmit,
  handleDelete,
  handleDeleteMediaAsset,
  handleDownloadMedia,
  handleRefreshMedia,
  handleRetryMediaProcessing,
  handleSelectAllDeadLetter,
  handleSubmit,
  handleToggleDeadLetterSelection,
  handleUpload,
  locale,
  locationReviewForm,
  mediaIssueCopy,
  panelCopy,
  refreshingMediaId,
  reminderForm,
  retryingMediaId,
  saving,
  savingReminder,
  selectedDeadLetterIds,
  selectedLocationHistory,
  selectedLocationReview,
  selectedRecord,
  selectedRecordMediaSizeLabel,
  setForm,
  setLocationReviewForm,
  setReminderForm,
  summarizeHistoryActionLabel,
  uploading,
}: BuildRecordEditorWorkspacePropsInput): RecordEditorWorkspaceProps {
  const copyProps = buildRecordEditorWorkspaceCopyProps({ detailCopy });
  const baseProps = buildRecordEditorWorkspaceBaseProps({
    authToken,
    bulkRetryingDeadLetter,
    canWriteWorkspace,
    deleting,
    deletingMediaId,
    downloadingMediaId,
    error,
    form,
    formatFileCountLabel,
    formatHistoryTimestampLabel,
    formatReminderEnabledLabel,
    formatReminderStatusLabel,
    formatReminderTimestampLabel,
    formatReviewStatusLabel,
    locale,
    locationReviewForm,
    mediaAssets,
    mediaDeadLetterOverview,
    mediaIssueCopy,
    mediaProcessingOverview,
    mediaStorageSummary,
    panelCopy,
    refreshingMediaId,
    reminderForm,
    reminders,
    retryingMediaId,
    saving,
    savingReminder,
    selectedDeadLetterIds,
    selectedLocationHistory,
    selectedLocationReview,
    selectedRecord,
    selectedRecordMediaSizeLabel,
    setForm,
    setLocationReviewForm,
    setReminderForm,
    summarizeHistoryActionLabel,
    uploading,
    workspaceId,
  });
  const actionProps = buildRecordEditorWorkspaceActionProps({
    handleBulkRetryDeadLetter,
    handleClearDeadLetterSelection,
    handleCreateReminderSubmit,
    handleDelete,
    handleDeleteMediaAsset,
    handleDownloadMedia,
    handleRefreshMedia,
    handleRetryMediaProcessing,
    handleSelectAllDeadLetter,
    handleSubmit,
    handleToggleDeadLetterSelection,
    handleUpload,
    onDeleteReminder,
    onUpdateReminder,
  });

  return {
    ...baseProps,
    ...copyProps,
    ...actionProps,
  };
}
