import type { Dispatch, SetStateAction } from "react";
import type { LocaleCode } from "../lib/locale";
import type { LocationReviewFormState, RecordFormState, ReminderFormState } from "../lib/record-panel-forms";
import type { MediaIssueCopy } from "../lib/record-panel-ui";
import type { LocationHistoryEntry, LocationReview, MediaAsset, MediaDeadLetterOverview, MediaProcessingOverview, MediaStorageSummary, RecordItem, ReminderItem } from "../lib/types";
export type RecordEditorWorkspaceDataProps = {
  authToken: string | null;
  canWriteWorkspace: boolean;
  workspaceId: string;
  locale: LocaleCode;
  selectedRecord: RecordItem | null;
  form: RecordFormState;
  setForm: Dispatch<SetStateAction<RecordFormState>>;
  locationReviewForm: LocationReviewFormState;
  setLocationReviewForm: Dispatch<SetStateAction<LocationReviewFormState>>;
  reminderForm: ReminderFormState;
  setReminderForm: Dispatch<SetStateAction<ReminderFormState>>;
  error: string;
  saving: boolean;
  deleting: boolean;
  uploading: boolean;
  savingReminder: boolean;
  bulkRetryingDeadLetter: boolean;
  downloadingMediaId: string | null;
  refreshingMediaId: string | null;
  retryingMediaId: string | null;
  deletingMediaId: string | null;
  selectedDeadLetterIds: string[];
  selectedRecordMediaSizeLabel: string;
  mediaAssets: MediaAsset[];
  mediaDeadLetterOverview: MediaDeadLetterOverview | null;
  mediaIssueCopy: MediaIssueCopy;
  mediaProcessingOverview: MediaProcessingOverview | null;
  mediaStorageSummary: MediaStorageSummary | null;
  reminders: ReminderItem[];
  selectedLocationHistory: LocationHistoryEntry[];
  selectedLocationReview: LocationReview | null;
  formatFileCountLabel: (count: number) => string;
  formatHistoryTimestampLabel: (value?: string | null) => string;
  formatReminderEnabledLabel: (value: boolean) => string;
  formatReminderStatusLabel: (value: string) => string;
  formatReminderTimestampLabel: (value: string) => string;
  formatReviewStatusLabel: (value?: string | null) => string;
  summarizeHistoryActionLabel: (entry: LocationHistoryEntry) => string;
};
