import type { RecordMediaSelectedContentProps } from "./record-media-selected-content.types";
import type { RecordMediaToolsProps } from "./record-media-tools.types";

export function buildRecordMediaToolsActionsProps({
  canWriteWorkspace,
  deleteButtonLabel,
  deleting,
  error,
  hasSelectedRecord,
  onDelete,
  onUpload,
  saveButtonLabel,
  saving,
  uploadAttachmentLabel,
  uploading,
  uploadingMediaLabel,
}: RecordMediaToolsProps) {
  return {
    canWriteWorkspace,
    deleteButtonLabel,
    deleting,
    error,
    hasSelectedRecord,
    onDelete,
    onUpload,
    saveButtonLabel,
    saving,
    uploadAttachmentLabel,
    uploading,
    uploadingMediaLabel,
  };
}

export function buildRecordMediaSelectedContentProps(
  props: RecordMediaToolsProps,
): RecordMediaSelectedContentProps {
  return {
    allTrackedFilesPresentLabel: props.allTrackedFilesPresentLabel,
    authToken: props.authToken,
    bulkRetryingDeadLetter: props.bulkRetryingDeadLetter,
    canWriteWorkspace: props.canWriteWorkspace,
    deletingMediaId: props.deletingMediaId,
    downloadingMediaId: props.downloadingMediaId,
    formatFileCountLabel: props.formatFileCountLabel,
    formatHistoryTimestampLabel: props.formatHistoryTimestampLabel,
    largestFilePrefixLabel: props.largestFilePrefixLabel,
    locale: props.locale,
    localLabel: props.localLabel,
    mediaAssets: props.mediaAssets,
    mediaDeadLetterOverview: props.mediaDeadLetterOverview,
    mediaIssueCopy: props.mediaIssueCopy,
    mediaProcessingOverview: props.mediaProcessingOverview,
    mediaStorageSummary: props.mediaStorageSummary,
    missingFilesLabel: props.missingFilesLabel,
    needsAttentionLabel: props.needsAttentionLabel,
    noMediaLabel: props.noMediaLabel,
    onBulkRetryAllDeadLetter: props.onBulkRetryAllDeadLetter,
    onBulkRetrySelectedDeadLetter: props.onBulkRetrySelectedDeadLetter,
    onClearDeadLetterSelection: props.onClearDeadLetterSelection,
    onDeleteMediaAsset: props.onDeleteMediaAsset,
    onDownloadMedia: props.onDownloadMedia,
    onRefreshMedia: props.onRefreshMedia,
    onRetryMediaProcessing: props.onRetryMediaProcessing,
    onSelectAllDeadLetter: props.onSelectAllDeadLetter,
    onToggleDeadLetterSelection: props.onToggleDeadLetterSelection,
    processingCompletedLabel: props.processingCompletedLabel,
    queuedLabel: props.queuedLabel,
    queueStateLabel: props.queueStateLabel,
    refreshingMediaId: props.refreshingMediaId,
    remoteLabel: props.remoteLabel,
    retryingMediaId: props.retryingMediaId,
    selectedDeadLetterIds: props.selectedDeadLetterIds,
    selectedRecordMediaSizeLabel: props.selectedRecordMediaSizeLabel,
    storageHealthLabel: props.storageHealthLabel,
    storageMixLabel: props.storageMixLabel,
    thisRecordMediaLabel: props.thisRecordMediaLabel,
    workspaceId: props.workspaceId,
    workspaceStorageLabel: props.workspaceStorageLabel,
  };
}
