"use client";

import type { RecordEditorSupportToolsProps } from "./record-editor-support-tools.types";

export function buildRecordMediaToolsProps({
  authToken,
  bulkRetryingDeadLetter,
  canWriteWorkspace,
  deleting,
  deletingMediaId,
  downloadingMediaId,
  error,
  formatFileCountLabel,
  formatHistoryTimestampLabel,
  largestFilePrefixLabel,
  locale,
  mediaAssets,
  mediaDeadLetterOverview,
  mediaIssueCopy,
  mediaProcessingOverview,
  mediaStorageSummary,
  noMediaLabel,
  onBulkRetryAllDeadLetter,
  onBulkRetrySelectedDeadLetter,
  onClearDeadLetterSelection,
  onDelete,
  onDeleteMediaAsset,
  onDownloadMedia,
  onRefreshMedia,
  onRetryMediaProcessing,
  onSelectAllDeadLetter,
  onToggleDeadLetterSelection,
  onUpload,
  panelCopy,
  refreshingMediaId,
  retryingMediaId,
  saving,
  selectedDeadLetterIds,
  selectedRecord,
  selectedRecordMediaSizeLabel,
  uploading,
  workspaceId,
}: RecordEditorSupportToolsProps) {
  return {
    allTrackedFilesPresentLabel: panelCopy.allTrackedFilesPresent,
    authToken,
    bulkRetryingDeadLetter,
    canWriteWorkspace,
    deleteButtonLabel: deleting ? panelCopy.deleting : panelCopy.deleteRecord,
    deleting,
    deletingMediaId,
    downloadingMediaId,
    error,
    formatFileCountLabel,
    formatHistoryTimestampLabel,
    hasSelectedRecord: Boolean(selectedRecord),
    largestFilePrefixLabel,
    localLabel: panelCopy.local,
    locale,
    mediaAssets,
    mediaDeadLetterOverview,
    mediaIssueCopy,
    mediaProcessingOverview,
    mediaStorageSummary,
    missingFilesLabel: panelCopy.missingFiles,
    needsAttentionLabel: panelCopy.needsAttention,
    noMediaLabel,
    onBulkRetryAllDeadLetter,
    onBulkRetrySelectedDeadLetter,
    onClearDeadLetterSelection,
    onDelete,
    onDeleteMediaAsset,
    onDownloadMedia,
    onRefreshMedia,
    onRetryMediaProcessing,
    onSelectAllDeadLetter,
    onToggleDeadLetterSelection,
    onUpload,
    processingCompletedLabel: panelCopy.processingCompleted,
    queuedLabel: panelCopy.queued,
    queueStateLabel: panelCopy.queueState,
    refreshingMediaId,
    remoteLabel: panelCopy.remote,
    retryingMediaId,
    saveButtonLabel: saving ? panelCopy.saving : selectedRecord ? panelCopy.updateRecord : panelCopy.createRecord,
    saving,
    selectedDeadLetterIds,
    selectedRecordMediaSizeLabel,
    storageHealthLabel: panelCopy.storageHealth,
    storageMixLabel: panelCopy.storageMix,
    thisRecordMediaLabel: panelCopy.thisRecordMedia,
    uploadAttachmentLabel: panelCopy.uploadAttachment,
    uploading,
    uploadingMediaLabel: panelCopy.uploadingMedia,
    workspaceId,
    workspaceStorageLabel: panelCopy.workspaceStorage,
  };
}
