import type {
  BuildRecordBrowseWorkspacePropsInput,
  RecordBrowseWorkspaceProps,
} from "./record-panel-v2-workspace-props.types";

export function buildRecordBrowseWorkspaceProps({
  canWriteWorkspace,
  records,
  timelineDays,
  selectedRecordId,
  recordFilter,
  searchPresets,
  onApplyLocationFilter,
  onApplyRecordFilter,
  onResetFilter,
  onSelectRecord,
  avoidCount,
  detailCopy,
  filterDraft,
  filteringRecords,
  foodCount,
  form,
  formatAvoidCountLabel,
  formatRecordTimestampLabel,
  formatReviewStatusLabel,
  formatTimelineCountLabel,
  formatTimelineDateLabel,
  handleApplyFilter,
  handleDeletePreset,
  handleSavePreset,
  panelCopy,
  presetName,
  savingSearchPreset,
  setFilterDraft,
  setForm,
  setPresetName,
  setViewMode,
  summarizeRecordFilterLabel,
  viewMode,
}: BuildRecordBrowseWorkspacePropsInput): RecordBrowseWorkspaceProps {
  return {
    applyPresetLabel: panelCopy.applyPreset,
    avoidCount,
    avoidRecordLabel: detailCopy.avoidLabel,
    avoidStatsLabel: panelCopy.avoid,
    canWriteWorkspace,
    currentFilterSummary: summarizeRecordFilterLabel(recordFilter),
    deletePresetLabel: panelCopy.deletePreset,
    draftLocation: canWriteWorkspace ? form.location ?? null : null,
    filteringRecords,
    filterDraft,
    flatListViewLabel: detailCopy.flatListView,
    foodCount,
    foodLabel: panelCopy.food,
    formatAvoidCountLabel,
    formatRecordTimestampLabel,
    formatReviewStatusLabel,
    formatTimelineCountLabel,
    formatTimelineDateLabel,
    mapPrefixLabel: detailCopy.mapPrefix,
    noContentLabel: detailCopy.noContent,
    noRecordsLabel: detailCopy.noRecords,
    noSavedFiltersLabel: panelCopy.noSavedFilters,
    onApplyFilter: handleApplyFilter,
    onApplyLocationFilter,
    onApplyPreset: onApplyRecordFilter,
    onDeletePreset: handleDeletePreset,
    onDraftLocationChange: canWriteWorkspace
      ? (nextLocation) =>
          setForm((prev) => ({
            ...prev,
            location: nextLocation,
          }))
      : undefined,
    onResetFilter,
    onSavePreset: handleSavePreset,
    onSelectRecord,
    panelCopy,
    presetName,
    ratingPrefixLabel: detailCopy.ratingPrefix,
    recordFilter,
    records,
    savedPresetLabel: panelCopy.savedPreset,
    savingSearchPreset,
    searchPresets,
    selectedRecordId,
    setFilterDraft,
    setPresetName,
    setViewMode,
    summarizeRecordFilterLabel,
    timelineDayLabel: detailCopy.timelineDayLabel,
    timelineDays,
    timelineViewLabel: detailCopy.timelineView,
    unknownPlaceLabel: detailCopy.unknownPlace,
    untitledRecordLabel: detailCopy.untitledRecord,
    viewMode,
    visibleRecordCount: records.length,
    visibleRecordsLabel: panelCopy.visibleRecords,
  };
}
