"use client";

import type { RecordEditorSupportToolsProps } from "./record-editor-support-tools.types";

export function buildRecordReminderToolsProps({
  canWriteWorkspace,
  channelInAppLabel,
  channelLabel,
  createReminderLabel,
  deleteReminderLabel,
  enableReminderLabel,
  formatReminderEnabledLabel,
  formatReminderStatusLabel,
  formatReminderTimestampLabel,
  markReminderDoneLabel,
  noRemindersLabel,
  onCreateReminder,
  onDeleteReminder,
  onUpdateReminder,
  pauseReminderLabel,
  reminderForm,
  reminderNoteLabel,
  reminderNotePlaceholder,
  reminderSectionDescription,
  reminderSectionTitle,
  reminderTitleLabel,
  reminderTitlePlaceholder,
  remindAtLabel,
  reminders,
  savingReminder,
  savingReminderLabel,
  selectedRecord,
  setReminderForm,
  untitledReminderLabel,
}: RecordEditorSupportToolsProps) {
  return {
    canWriteWorkspace,
    channelInApp: channelInAppLabel,
    channelLabel,
    createReminderLabel,
    deleteReminderLabel,
    enableReminderLabel,
    formatReminderEnabledLabel,
    formatReminderStatusLabel,
    formatReminderTimestampLabel,
    hasSelectedRecord: Boolean(selectedRecord),
    markReminderDoneLabel,
    noRemindersLabel,
    onCreateReminder,
    onDeleteReminder,
    onUpdateReminder,
    pauseReminderLabel,
    reminderForm,
    reminderNoteLabel,
    reminderNotePlaceholder,
    reminderSectionDescription,
    reminderSectionTitle,
    reminderTitleLabel,
    reminderTitlePlaceholder,
    remindAtLabel,
    reminders,
    savingReminder,
    savingReminderLabel,
    selectedRecordTitle: selectedRecord?.title ?? null,
    setReminderForm,
    untitledReminderLabel,
  };
}
