"use client";

import type { RecordEditorWorkspaceProps } from "./record-editor-workspace.types";

export type RecordEditorMediaToolsProps = Pick<
  RecordEditorWorkspaceProps,
  | "authToken"
  | "bulkRetryingDeadLetter"
  | "canWriteWorkspace"
  | "deleting"
  | "deletingMediaId"
  | "downloadingMediaId"
  | "error"
  | "formatFileCountLabel"
  | "formatHistoryTimestampLabel"
  | "largestFilePrefixLabel"
  | "locale"
  | "mediaAssets"
  | "mediaDeadLetterOverview"
  | "mediaIssueCopy"
  | "mediaProcessingOverview"
  | "mediaStorageSummary"
  | "noMediaLabel"
  | "onBulkRetryAllDeadLetter"
  | "onBulkRetrySelectedDeadLetter"
  | "onClearDeadLetterSelection"
  | "onDelete"
  | "onDeleteMediaAsset"
  | "onDownloadMedia"
  | "onRefreshMedia"
  | "onRetryMediaProcessing"
  | "onSelectAllDeadLetter"
  | "onToggleDeadLetterSelection"
  | "onUpload"
  | "panelCopy"
  | "refreshingMediaId"
  | "retryingMediaId"
  | "saving"
  | "selectedDeadLetterIds"
  | "selectedRecord"
  | "selectedRecordMediaSizeLabel"
  | "uploading"
  | "workspaceId"
>;
