import type { WorkspaceEntryCopyMap } from "./workspace-entry-copy.types";

export const WORKSPACE_ENTRY_COPY: WorkspaceEntryCopyMap = {
  "zh-CN": {
    eyebrow: "工作区",
    title: "控制中心",
    signedInAs: "当前登录",
    signedIn: "已登录",
    signOut: "退出登录",
    createEyebrow: "创建",
    createTitle: "新建工作区",
    name: "名称",
    slugPreview: "Slug 预览",
    createWorkspace: "创建工作区",
    importEyebrow: "导入",
    importTitle: "从导出 ZIP 恢复",
    importArchive: "导入 ZIP",
    importName: "新工作区名称（可选）",
    importSlug: "新工作区 Slug（可选）",
    importWorkspace: "导入工作区",
    queueImportJob: "加入导入队列",
    joinEyebrow: "加入",
    joinTitle: "共享工作区",
    sharePlaceholder: "粘贴分享 token 或 /share/... 链接",
    previewShare: "预览分享",
    joinWorkspace: "加入工作区",
    listEyebrow: "列表",
    listTitle: "你的工作区",
    openWorkspace: "打开工作区",
    settings: "设置",
    jobsEyebrow: "任务",
    jobsTitle: "最近后台任务",
    refreshJobs: "刷新任务",
    openImportedWorkspace: "打开导入结果",
    downloadExportJob: "下载导出结果",
    noJobs: "当前没有后台任务。",
    noWorkspace: "还没有工作区，先创建或导入一个。",
    loading: "正在加载工作区列表...",
    loadFailed: "加载工作区列表失败",
    previewShareFailed: "预览分享链接失败",
    joinSharedWorkspaceFailed: "加入共享工作区失败",
    createWorkspaceFailed: "创建工作区失败",
    importWorkspaceFailed: "导入工作区失败",
    createImportJobFailed: "创建导入任务失败",
    downloadTransferJobFailed: "下载传输任务结果失败",
  },
  en: {
    eyebrow: "Workspace",
    title: "Control Center",
    signedInAs: "Signed in as",
    signedIn: "Signed in",
    signOut: "Sign Out",
    createEyebrow: "Create",
    createTitle: "New workspace",
    name: "Name",
    slugPreview: "Slug preview",
    createWorkspace: "Create workspace",
    importEyebrow: "Import",
    importTitle: "Restore from export ZIP",
    importArchive: "Import ZIP",
    importName: "New workspace name (optional)",
    importSlug: "New workspace slug (optional)",
    importWorkspace: "Import workspace",
    queueImportJob: "Queue import job",
    joinEyebrow: "Join",
    joinTitle: "Shared workspace",
    sharePlaceholder: "Paste share token or /share/... link",
    previewShare: "Preview share",
    joinWorkspace: "Join workspace",
    listEyebrow: "List",
    listTitle: "Your workspaces",
    openWorkspace: "Open workspace",
    settings: "Settings",
    jobsEyebrow: "Jobs",
    jobsTitle: "Recent background jobs",
    refreshJobs: "Refresh jobs",
    openImportedWorkspace: "Open imported workspace",
    downloadExportJob: "Download export result",
    noJobs: "No background jobs yet.",
    noWorkspace: "No workspace yet. Create or import one first.",
    loading: "Loading your workspace list...",
    loadFailed: "Failed to load workspace list",
    previewShareFailed: "Failed to preview share link",
    joinSharedWorkspaceFailed: "Failed to join shared workspace",
    createWorkspaceFailed: "Failed to create workspace",
    importWorkspaceFailed: "Failed to import workspace",
    createImportJobFailed: "Failed to create import job",
    downloadTransferJobFailed: "Failed to download transfer job result",
  },
  ja: {
    eyebrow: "ワークスペース",
    title: "コントロールセンター",
    signedInAs: "ログイン中",
    signedIn: "ログイン済み",
    signOut: "ログアウト",
    createEyebrow: "作成",
    createTitle: "新しいワークスペース",
    name: "名前",
    slugPreview: "Slug プレビュー",
    createWorkspace: "ワークスペースを作成",
    importEyebrow: "インポート",
    importTitle: "エクスポート ZIP から復元",
    importArchive: "ZIP を選択",
    importName: "新しいワークスペース名（任意）",
    importSlug: "新しいワークスペース slug（任意）",
    importWorkspace: "ワークスペースをインポート",
    queueImportJob: "インポートジョブ追加",
    joinEyebrow: "参加",
    joinTitle: "共有ワークスペース",
    sharePlaceholder: "共有 token または /share/... リンクを貼り付け",
    previewShare: "共有を確認",
    joinWorkspace: "ワークスペースに参加",
    listEyebrow: "一覧",
    listTitle: "あなたのワークスペース",
    openWorkspace: "開く",
    settings: "設定",
    jobsEyebrow: "ジョブ",
    jobsTitle: "最近のバックグラウンドジョブ",
    refreshJobs: "ジョブを更新",
    openImportedWorkspace: "インポート結果を開く",
    downloadExportJob: "エクスポート結果を取得",
    noJobs: "バックグラウンドジョブはまだありません。",
    noWorkspace: "まだワークスペースがありません。先に作成またはインポートしてください。",
    loading: "ワークスペース一覧を読み込み中...",
    loadFailed: "ワークスペース一覧の読み込みに失敗しました",
    previewShareFailed: "共有リンクの確認に失敗しました",
    joinSharedWorkspaceFailed: "共有ワークスペースへの参加に失敗しました",
    createWorkspaceFailed: "ワークスペースの作成に失敗しました",
    importWorkspaceFailed: "ワークスペースのインポートに失敗しました",
    createImportJobFailed: "インポートジョブの作成に失敗しました",
    downloadTransferJobFailed: "転送ジョブ結果のダウンロードに失敗しました",
  },
};

export const WORKSPACE_ENTRY_DISPLAY_COPY: WorkspaceEntryCopyMap = {
  "zh-CN": {
    eyebrow: "工作区",
    title: "控制中心",
    signedInAs: "当前登录",
    signedIn: "已登录",
    signOut: "退出登录",
    createEyebrow: "创建",
    createTitle: "新建工作区",
    name: "名称",
    slugPreview: "Slug 预览",
    createWorkspace: "创建工作区",
    importEyebrow: "导入",
    importTitle: "从导出 ZIP 恢复",
    importArchive: "导入 ZIP",
    importName: "新工作区名称（可选）",
    importSlug: "新工作区 Slug（可选）",
    importWorkspace: "导入工作区",
    queueImportJob: "加入导入队列",
    joinEyebrow: "加入",
    joinTitle: "共享工作区",
    sharePlaceholder: "粘贴分享 token 或 /share/... 链接",
    previewShare: "预览分享",
    joinWorkspace: "加入工作区",
    listEyebrow: "列表",
    listTitle: "你的工作区",
    openWorkspace: "打开工作区",
    settings: "设置",
    jobsEyebrow: "任务",
    jobsTitle: "最近后台任务",
    refreshJobs: "刷新任务",
    openImportedWorkspace: "打开导入结果",
    downloadExportJob: "下载导出结果",
    noJobs: "当前没有后台任务。",
    noWorkspace: "还没有工作区，先创建或导入一个。",
    loading: "正在加载工作区列表...",
    loadFailed: "加载工作区列表失败",
    previewShareFailed: "预览分享链接失败",
    joinSharedWorkspaceFailed: "加入共享工作区失败",
    createWorkspaceFailed: "创建工作区失败",
    importWorkspaceFailed: "导入工作区失败",
    createImportJobFailed: "创建导入任务失败",
    downloadTransferJobFailed: "下载传输任务结果失败",
  },
  en: {
    eyebrow: "Workspace",
    title: "Control Center",
    signedInAs: "Signed in as",
    signedIn: "Signed in",
    signOut: "Sign Out",
    createEyebrow: "Create",
    createTitle: "New workspace",
    name: "Name",
    slugPreview: "Slug preview",
    createWorkspace: "Create workspace",
    importEyebrow: "Import",
    importTitle: "Restore from export ZIP",
    importArchive: "Import ZIP",
    importName: "New workspace name (optional)",
    importSlug: "New workspace slug (optional)",
    importWorkspace: "Import workspace",
    queueImportJob: "Queue import job",
    joinEyebrow: "Join",
    joinTitle: "Shared workspace",
    sharePlaceholder: "Paste share token or /share/... link",
    previewShare: "Preview share",
    joinWorkspace: "Join workspace",
    listEyebrow: "List",
    listTitle: "Your workspaces",
    openWorkspace: "Open workspace",
    settings: "Settings",
    jobsEyebrow: "Jobs",
    jobsTitle: "Recent background jobs",
    refreshJobs: "Refresh jobs",
    openImportedWorkspace: "Open imported workspace",
    downloadExportJob: "Download export result",
    noJobs: "No background jobs yet.",
    noWorkspace: "No workspace yet. Create or import one first.",
    loading: "Loading your workspace list...",
    loadFailed: "Failed to load workspace list",
    previewShareFailed: "Failed to preview share link",
    joinSharedWorkspaceFailed: "Failed to join shared workspace",
    createWorkspaceFailed: "Failed to create workspace",
    importWorkspaceFailed: "Failed to import workspace",
    createImportJobFailed: "Failed to create import job",
    downloadTransferJobFailed: "Failed to download transfer job result",
  },
  ja: {
    eyebrow: "ワークスペース",
    title: "コントロールセンター",
    signedInAs: "ログイン中",
    signedIn: "ログイン済み",
    signOut: "ログアウト",
    createEyebrow: "作成",
    createTitle: "新しいワークスペース",
    name: "名前",
    slugPreview: "Slug プレビュー",
    createWorkspace: "ワークスペースを作成",
    importEyebrow: "インポート",
    importTitle: "エクスポート ZIP から復元",
    importArchive: "ZIP を選択",
    importName: "新しいワークスペース名（任意）",
    importSlug: "新しいワークスペース slug（任意）",
    importWorkspace: "ワークスペースをインポート",
    queueImportJob: "インポートジョブ追加",
    joinEyebrow: "参加",
    joinTitle: "共有ワークスペース",
    sharePlaceholder: "共有 token または /share/... リンクを貼り付け",
    previewShare: "共有を確認",
    joinWorkspace: "ワークスペースに参加",
    listEyebrow: "一覧",
    listTitle: "あなたのワークスペース",
    openWorkspace: "開く",
    settings: "設定",
    jobsEyebrow: "ジョブ",
    jobsTitle: "最近のバックグラウンドジョブ",
    refreshJobs: "ジョブを更新",
    openImportedWorkspace: "インポート結果を開く",
    downloadExportJob: "エクスポート結果を取得",
    noJobs: "バックグラウンドジョブはまだありません。",
    noWorkspace: "まだワークスペースがありません。先に作成またはインポートしてください。",
    loading: "ワークスペース一覧を読み込み中...",
    loadFailed: "ワークスペース一覧の読み込みに失敗しました",
    previewShareFailed: "共有リンクの確認に失敗しました",
    joinSharedWorkspaceFailed: "共有ワークスペースへの参加に失敗しました",
    createWorkspaceFailed: "ワークスペースの作成に失敗しました",
    importWorkspaceFailed: "ワークスペースのインポートに失敗しました",
    createImportJobFailed: "インポートジョブの作成に失敗しました",
    downloadTransferJobFailed: "転送ジョブ結果のダウンロードに失敗しました",
  },
};
