"use client";

import type {
  WorkspaceShellPanelsProps,
} from "./workspace-shell-client-props.types";
import type { BuildWorkspaceShellPanelsPropsInput } from "./workspace-shell-client-panels-props.types";

export function buildWorkspaceShellPanelsProps(
  input: BuildWorkspaceShellPanelsPropsInput,
): WorkspaceShellPanelsProps {
  return {
    activeConversationId: input.activeConversationId,
    auditLogs: input.auditLogs,
    authToken: input.token,
    canManageSharing: input.canManageSharing,
    canManageWorkspace: input.canManageWorkspace,
    canWriteWorkspace: input.canWriteWorkspace,
    conversations: input.conversations,
    filteringRecords: input.filteringRecords,
    knowledgeStats: input.knowledgeStats,
    latestSharePath: input.latestSharePath,
    mediaAssets: input.mediaAssets,
    mediaDeadLetterOverview: input.mediaDeadLetterOverview,
    mediaProcessingOverview: input.mediaProcessingOverview,
    mediaStorageSummary: input.mediaStorageSummary,
    messages: input.messages,
    notifications: input.notifications,
    onApplyLocationFilter: input.actions.handleApplyLocationFilter,
    onApplyRecordFilter: input.actions.handleApplyRecordFilter,
    onBulkRetryMediaDeadLetter: input.actions.handleBulkRetryMediaDeadLetter,
    onCreateConversation: input.actions.handleCreateConversation,
    onCreateReminder: input.actions.handleCreateReminder,
    onCreateSearchPreset: input.actions.handleCreateSearchPreset,
    onCreateShareLink: input.actions.handleCreateShareLink,
    onDeleteMedia: input.actions.handleDeleteMedia,
    onDeleteRecord: input.actions.handleDeleteRecord,
    onDeleteReminder: input.actions.handleDeleteReminder,
    onDeleteSearchPreset: input.actions.handleDeleteSearchPreset,
    onDisableShareLink: input.actions.handleDisableShareLink,
    onMarkNotificationRead: input.actions.handleMarkNotificationRead,
    onRefreshAuditLogs: input.actions.handleRefreshAuditLogs,
    onRefreshMediaStatus: input.actions.handleRefreshMediaStatus,
    onReindexKnowledge: input.actions.handleReindexKnowledge,
    onResetFilter: input.actions.handleResetFilter,
    onRetryMedia: input.actions.handleRetryMedia,
    onSaveRecord: input.actions.handleSaveRecord,
    onSelectConversation: input.actions.handleSelectConversation,
    onSelectRecord: input.setSelectedRecordId,
    onSendMessage: input.actions.handleSendMessage,
    onSyncNotifications: input.actions.handleSyncNotifications,
    onUpdateReminder: input.actions.handleUpdateReminder,
    onUploadMedia: input.actions.handleUploadMedia,
    recordFilter: input.recordFilter,
    records: input.visibleRecords,
    reminders: input.reminders,
    savingSearchPreset: input.savingSearchPreset,
    searchPresets: input.searchPresets,
    selectedRecordId: input.selectedRecordId,
    shareLinks: input.shareLinks,
    timelineDays: input.timelineDays,
    workspaceId: input.workspaceId,
    workspaceRole: input.workspace?.role ?? "viewer",
  };
}
