"use client";

import type { BuildWorkspaceShellActionsInput } from "./workspace-shell-client-actions-input.types";

export function buildWorkspaceShellActionsInput({
  refreshers,
  activeConversationId,
  canManageSharing,
  canManageWorkspace,
  canWriteWorkspace,
  conversations,
  recordFilter,
  records,
  selectedRecordId,
  setActiveConversationId,
  setConversations,
  setFilteringRecords,
  setKnowledgeStats,
  setLatestSharePath,
  setMessages,
  setRecordFilter,
  setSavingSearchPreset,
  setSelectedRecordId,
  setTimelineDays,
  setVisibleRecords,
  token,
  workspaceId,
}: BuildWorkspaceShellActionsInput) {
  return {
    token,
    workspaceId,
    activeConversationId,
    canWriteWorkspace,
    canManageWorkspace,
    canManageSharing,
    conversationsCount: conversations.length,
    recordFilter,
    records,
    selectedRecordId,
    refreshRecords: refreshers.refreshRecords,
    refreshMedia: refreshers.refreshMedia,
    refreshMediaStorageSummary: refreshers.refreshMediaStorageSummary,
    refreshMediaProcessingOverview: refreshers.refreshMediaProcessingOverview,
    refreshMediaDeadLetterOverview: refreshers.refreshMediaDeadLetterOverview,
    refreshReminders: refreshers.refreshReminders,
    refreshNotifications: refreshers.refreshNotifications,
    refreshKnowledge: refreshers.refreshKnowledge,
    refreshSearchPresets: refreshers.refreshSearchPresets,
    refreshAuditLogs: refreshers.refreshAuditLogs,
    refreshShareLinks: refreshers.refreshShareLinks,
    syncDueNotifications: refreshers.syncDueNotifications,
    loadConversationMessages: refreshers.loadConversationMessages,
    setMessages,
    setVisibleRecords,
    setTimelineDays,
    setSelectedRecordId,
    setConversations,
    setActiveConversationId,
    setRecordFilter,
    setFilteringRecords,
    setSavingSearchPreset,
    setKnowledgeStats,
    setLatestSharePath,
    initialRecordFilter: refreshers.initialRecordFilter,
  };
}
