import type { LocaleCode } from "../lib/locale";

export type WorkspaceMediaRetentionCopy = {
  eyebrow: string;
  title: string;
  description: string;
  refresh: string;
  refreshing: string;
  threshold: string;
  totalTracked: string;
  agedMedia: string;
  archivedMedia: string;
  remoteMedia?: string;
  storageRisk: string;
  noLargestItems: string;
  noCandidates: string;
  largestTitle: string;
  candidatesTitle: string;
  orphanFiles: string;
  missingFiles: string;
  oldestMedia: string;
  cleanupNote: string;
  ageDays: string;
  createdAt: string;
  missing: string;
  archived: string;
  primary: string;
  remoteReference?: string;
  allHealthy: string;
  days: string;
  loadFailed: string;
  ownerActions: string;
  editorReadOnly: string;
  selectLabel: string;
  selectAll: string;
  clearSelection: string;
  selectedSummary: string;
  archiveSelected: string;
  deleteSelected: string;
  deleteOrphans: string;
  processing: string;
  actionFailed: string;
  archiveCompleted: string;
  cleanupCompleted: string;
  archiveConfirmSelected: string;
  cleanupConfirmSelected: string;
  cleanupConfirmOrphans: string;
};

export type WorkspaceMediaRetentionCopyMap = Record<LocaleCode, WorkspaceMediaRetentionCopy>;
