"use client";

import type {
  WorkspaceShellPanelsProps,
} from "./workspace-shell-client-props.types";
import type { BuildWorkspaceShellPanelsPropsInput } from "./workspace-shell-client-panels-props.types";

export function buildWorkspaceShellPanelsProps({
  actions,
  activeConversationId,
  auditLogs,
  canManageSharing,
  canManageWorkspace,
  canWriteWorkspace,
  conversations,
  filteringRecords,
  knowledgeStats,
  latestSharePath,
  mediaAssets,
  mediaDeadLetterOverview,
  mediaProcessingOverview,
  mediaStorageSummary,
  messages,
  notifications,
  recordFilter,
  reminders,
  savingSearchPreset,
  searchPresets,
  selectedRecordId,
  setSelectedRecordId,
  shareLinks,
  timelineDays,
  token,
  visibleRecords,
  workspace,
  workspaceId,
}: BuildWorkspaceShellPanelsPropsInput): WorkspaceShellPanelsProps {
  return {
    activeConversationId,
    auditLogs,
    authToken: token,
    canManageSharing,
    canManageWorkspace,
    canWriteWorkspace,
    conversations,
    filteringRecords,
    knowledgeStats,
    latestSharePath,
    mediaAssets,
    mediaDeadLetterOverview,
    mediaProcessingOverview,
    mediaStorageSummary,
    messages,
    notifications,
    onApplyLocationFilter: actions.handleApplyLocationFilter,
    onApplyRecordFilter: actions.handleApplyRecordFilter,
    onBulkRetryMediaDeadLetter: actions.handleBulkRetryMediaDeadLetter,
    onCreateConversation: actions.handleCreateConversation,
    onCreateReminder: actions.handleCreateReminder,
    onCreateSearchPreset: actions.handleCreateSearchPreset,
    onCreateShareLink: actions.handleCreateShareLink,
    onDeleteMedia: actions.handleDeleteMedia,
    onDeleteRecord: actions.handleDeleteRecord,
    onDeleteReminder: actions.handleDeleteReminder,
    onDeleteSearchPreset: actions.handleDeleteSearchPreset,
    onDisableShareLink: actions.handleDisableShareLink,
    onMarkNotificationRead: actions.handleMarkNotificationRead,
    onRefreshAuditLogs: actions.handleRefreshAuditLogs,
    onRefreshMediaStatus: actions.handleRefreshMediaStatus,
    onReindexKnowledge: actions.handleReindexKnowledge,
    onResetFilter: actions.handleResetFilter,
    onRetryMedia: actions.handleRetryMedia,
    onSaveRecord: actions.handleSaveRecord,
    onSelectConversation: actions.handleSelectConversation,
    onSelectRecord: setSelectedRecordId,
    onSendMessage: actions.handleSendMessage,
    onSyncNotifications: actions.handleSyncNotifications,
    onUpdateReminder: actions.handleUpdateReminder,
    onUploadMedia: actions.handleUploadMedia,
    recordFilter,
    records: visibleRecords,
    reminders,
    savingSearchPreset,
    searchPresets,
    selectedRecordId,
    shareLinks,
    timelineDays,
    workspaceId,
    workspaceRole: workspace?.role ?? "viewer",
  };
}
