"use client";

import type { BuildWorkspaceShellEffectsInput } from "./workspace-shell-client-effects-input.types";

export function buildWorkspaceShellEffectsInput({
  router,
  selectedRecordId,
  setActiveConversationId,
  setAuditLogs,
  setConversations,
  setError,
  setKnowledgeStats,
  setLatestSharePath,
  setLoading,
  setMediaAssets,
  setMediaDeadLetterOverview,
  setMediaProcessingOverview,
  setMediaStorageSummary,
  setMessages,
  setNotifications,
  setRecords,
  setReminders,
  setSearchPresets,
  setSelectedRecordId,
  setShareLinks,
  setTimelineDays,
  setToken,
  setVisibleRecords,
  setWorkspace,
  token,
  workspaceId,
}: BuildWorkspaceShellEffectsInput) {
  return {
    router,
    workspaceId,
    token,
    selectedRecordId,
    setToken,
    setWorkspace,
    setRecords,
    setVisibleRecords,
    setTimelineDays,
    setConversations,
    setActiveConversationId,
    setMessages,
    setSelectedRecordId,
    setMediaAssets,
    setMediaDeadLetterOverview,
    setMediaProcessingOverview,
    setMediaStorageSummary,
    setReminders,
    setNotifications,
    setKnowledgeStats,
    setSearchPresets,
    setShareLinks,
    setLatestSharePath,
    setAuditLogs,
    setError,
    setLoading,
  };
}
